---
name: "ci / staging"

on:
    push:
        branches:
            - staging

jobs:
    paths-filter:
        runs-on: ubuntu-latest
        outputs:
            api: ${{ steps.filter.outputs.api }}
        steps:
            - uses: actions/checkout@v2
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  base: ${{ github.ref.staging }}
                  filters: |
                      api: 
                          - 'apps/api/**'

    api:
        runs-on: ubuntu-latest
        needs: paths-filter
        if: ${{needs.paths-filter.outputs.api == 'true'}}
        permissions:
            contents: read
            packages: write
            deployments: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Change working directory
              run: cd apps/api
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push container image
              uses: docker/build-push-action@v5
              with:
                  context: ./apps/api
                  build-contexts: |
                      oven/bun=docker-image://oven/bun:latest
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ghcr.io/nautilus/api:staging
