---
name: "ci / staging"

on:
    push:
        branches:
            - staging

jobs:
    paths-filter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  filters: |
                      api: 
                          - 'apps/api/**'

    test:
        runs-on: ubuntu-latest
        needs: paths-filter
        steps:
            - name: Test
              run: echo ${{needs.paths-filter.outputs.api}}
    api:
        runs-on: ubuntu-latest
        needs: paths-filter
        if: ${{needs.paths-filter.outputs.api == 'true'}}
        permissions:
            contents: read
            packages: write
            deployments: write

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push container image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64,mac/amd64,mac/arm64
                  push: true
                  tags: ghcr.io/nautilus/api:staging
